export type ServiceOffering = {
  title: string;
  featured?: boolean;
  image: string;
  bullets: string[];
};

export type ServiceEntry = {
  slug: string;
  /** Masonry / nav label */
  label: string;
  eyebrow: string;
  metaTitle: string;
  metaDescription: string;
  heroLines: [string, string];
  heroDescription: string;
  image: string;
  aspect: "short" | "mid" | "tall" | "wide";
  introTitle: string;
  introBody: string;
  introAside: string;
  menuTitle: string;
  menuLead: string;
  offerings: ServiceOffering[];
  whyEyebrow: string;
  whyTitle: string;
  whyLead: string;
  whyVisual: string;
  why: { title: string; text: string }[];
  ctaTitle: string;
  ctaBody: string;
  inquiryTitle: string;
  inquiryLead: string;
  bottomTitle: string;
  faqs: { q: string; a: string }[];
  contactTopic?: string;
};

const g = (a: string, b: string) =>
  `linear-gradient(145deg, ${a} 0%, #0a0a0a 55%), radial-gradient(circle at 70% 30%, ${b}, transparent 55%)`;

export const serviceCatalog: ServiceEntry[] = [
  {
    slug: "corporate",
    label: "Corporate Videos",
    eyebrow: "Corporate video editing",
    metaTitle: "Corporate Video Editing Services",
    metaDescription:
      "Brand-aligned corporate video finishing for explainers, internal comms, webinars, and pitches. Remote delivery with clear USD pricing.",
    heroLines: ["Structured corporate", "video finishing services"],
    heroDescription:
      "Brand-aligned corporate edits with clear review control — explainers, leadership interviews, webinars, pitches, and testimonials. Human editorial oversight and published USD pricing before Stripe Checkout.",
    image:
      "https://images.unsplash.com/photo-1573164713714-d95e436ab8d6?auto=format&fit=crop&w=900&q=80",
    aspect: "tall",
    introTitle: "Why corporate edits stall — and how we fix it",
    introBody:
      "Initiatives stall at editing: inconsistent brand alignment and fragmented review cycles. We combine structured intake, revision limits, and brand kits locked before work starts — so deliverables stay credible and on schedule.",
    introAside:
      "Built for agencies, enterprise marketing, HR / L&D, and professional services. Remote finishing for teams that need delivery discipline — not open-ended creative loops.",
    menuTitle: "Our Corporate Video Editing Services",
    menuLead: "Each offering lists exact work included — so Stripe checkout and stakeholders see the same scope.",
    offerings: [
      {
        title: "Corporate Explainer & Brand Story Finishing",
        featured: true,
        image: g("#1a2030", "rgba(227,6,19,0.35)"),
        bullets: [
          "Edit explainers from approved scripts, VO, and supplied footage",
          "Assemble brand stories with your visual assets and motion rules",
          "Apply typography, color systems, logo safe-zones, and graphic standards",
          "Deliver masters plus platform exports for web, LMS, and internal share",
        ],
      },
      {
        title: "Internal Comms & Executive Interviews",
        image: g("#201818", "rgba(255,138,0,0.25)"),
        bullets: [
          "Leadership updates and enterprise announcement cuts",
          "Interview continuity edits for clarity and pace",
          "Branded lower-thirds and compliance text as specified",
          "Audio normalize, color balance, drafts, and final masters",
        ],
      },
      {
        title: "Webinar & Knowledge Session Editing",
        image: g("#181a22", "rgba(56,120,180,0.35)"),
        bullets: [
          "Multi-speaker webinar clean-up and structure",
          "Slide sync with speaker footage",
          "Remove pauses, redundancies, and technical interruptions",
          "Full-length plus segmented exports for portals or campaigns",
        ],
      },
      {
        title: "Sales Pitch & Business Presentation Edits",
        image: g("#1a1418", "rgba(227,6,19,0.28)"),
        bullets: [
          "Turn recorded decks into structured pitch films",
          "Slide overlays, data callouts, and branded graphics",
          "Pace locked to narration and presentation timing",
          "CRM-ready and gated-share format packages",
        ],
      },
      {
        title: "Board / All-Hands Film Finishing",
        image: g("#14181a", "rgba(61,191,176,0.2)"),
        bullets: [
          "Town-hall and all-hands narrative structure",
          "Chapter markers and highlight cut-downs",
          "Caption packs for accessibility and archive",
          "Secure cloud delivery for restricted audiences",
        ],
      },
      {
        title: "Production Overflow & Post Support",
        image: g("#1a1814", "rgba(255,193,7,0.2)"),
        bullets: [
          "Edit raw footage from your production partners",
          "Follow agreed timelines, review cycles, and revision limits",
          "Documented version control across rounds",
          "Project notes and finals as defined in the engagement",
        ],
      },
    ],
    whyEyebrow: "Delivery control",
    whyTitle: "Why Teams Choose Our Corporate Finishing",
    whyLead: "Documented workflows and defined review controls — delivery discipline over open-ended creative cycles.",
    whyVisual: "linear-gradient(160deg,#2a1212,#111),radial-gradient(circle at 40% 40%,rgba(227,6,19,0.35),transparent 50%)",
    why: [
      { title: "Defined review hierarchies", text: "Edits move through agreed approval stages without informal revision loops." },
      { title: "Documented version control", text: "Tracked edit histories and clearly labeled versions across every review round." },
      { title: "Brand governance enforcement", text: "Typography, motion, and messaging stay locked to your brand kit." },
      { title: "Remote volume readiness", text: "Cloud handoff and queue visibility for campaigns and evergreen content." },
      { title: "Messaging-aligned formatting", text: "Pitches and announcements follow frameworks you provide." },
      { title: "Secure file handling", text: "Restricted-access handoff suitable for sensitive corporate content." },
    ],
    ctaTitle: "Strengthen delivery control with scoped corporate finishing.",
    ctaBody: "Defined intake, documented review cycles, and approval-ready outputs. Ready to outsource under a clear USD package or hourly quote?",
    inquiryTitle: "Request a Corporate Scope Call",
    inquiryLead: "Tell us volume, brand kit status, and deadlines. We confirm package or hours before Stripe.",
    bottomTitle: "Ready to lock a corporate finish?",
    contactTopic: "corporate",
    faqs: [
      { q: "Which factors influence corporate editing cost?", a: "Footage length, revision rounds, motion complexity, turnaround, and export formats. Quoted in USD before Stripe Checkout." },
      { q: "How is pricing structured?", a: "Hourly rates or per-project packages with revision limits. See Pricing and Checkout." },
      { q: "How long does a corporate finish take?", a: "Timelines are set at intake — typically aligned to published package ranges unless rush is scoped." },
      { q: "Do you work fully remote?", a: "Yes. Brief, upload, review, and delivery happen online via Drive, Dropbox, Frame.io, or similar." },
      { q: "What deliverables are included?", a: "Masters, platform exports, branded graphics integration, audio correction, and revision rounds listed in scope." },
    ],
  },
  {
    slug: "product",
    label: "Product Video",
    eyebrow: "Product video editing",
    metaTitle: "Product Video Editing Services",
    metaDescription:
      "Remote product video finishing for ecommerce, UGC, demos, launches, and ad clips with clear USD pricing.",
    heroLines: ["Product video finishing", "that sells, not just shows"],
    heroDescription:
      "Remote product post for ecommerce brands, agencies, and catalog teams — brand-consistent demos, UGC cuts, launches, and ad clips with human editorial oversight.",
    image:
      "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=900&q=80",
    aspect: "wide",
    introTitle: "Multi-platform product volume shouldn’t stall your catalog",
    introBody:
      "Managing product video across PDPs, ads, and campaigns creates post overhead. We finish product footage remotely with brand locks, platform packs, and clear revision limits.",
    introAside:
      "Built for ecommerce, D2C, agencies, and catalog teams that need publish-ready assets — starting from published packages or hourly rates.",
    menuTitle: "Product Video Editing Services That Sell",
    menuLead: "Showcase, instruct, and convert — scope listed clearly for Stripe and merchandising teams.",
    offerings: [
      { title: "Brand & Ecommerce Product Finishing", featured: true, image: g("#1a2030", "rgba(227,6,19,0.4)"), bullets: ["Shopify / Amazon / D2C export packs", "Branded intro/outro and LUT locks", "Close-up detailing and zoom beats", "Captions, titles, and thumbnail stills"] },
      { title: "UGC & Influencer Product Cuts", image: g("#201818", "rgba(255,138,0,0.28)"), bullets: ["Trim and sound-balance UGC to brand", "TikTok / Reels / Shorts ratios", "Captions, overlays, CTA end-cards", "Authenticity pacing with brand-safe grade"] },
      { title: "Product Demo & Instructional Editing", image: g("#181a22", "rgba(56,120,180,0.35)"), bullets: ["Step sequencing with text callouts", "Screen capture + motion callouts", "Spotlight beats on key features", "Training-ready masters + captions"] },
      { title: "Flagship Product Launch Films", image: g("#1a1418", "rgba(227,6,19,0.32)"), bullets: ["Multi-clip launch narratives", "Grade and reveal beats vs. brief", "Digital / event / paid masters", "Kinetic type scoped per engagement"] },
      { title: "Product Teasers & Ad Clip Editing", image: g("#14181a", "rgba(61,191,176,0.22)"), bullets: ["Beat-matched short-form teasers", "Benefit callouts and CTA frames", "Reels, pre-roll, carousel lengths", "Loudness packs for Meta / YT / TikTok"] },
      { title: "Animated & Explainer Product Edits", image: g("#1a1814", "rgba(255,193,7,0.22)"), bullets: ["Integrate supplied 2D/3D assets", "Explainer structure + data callouts", "Brand palettes and subtitle sync", "VO / music mix + SRT where scoped"] },
    ],
    whyEyebrow: "Why teams stay",
    whyTitle: "Why Choose Our Product Video Finishing",
    whyLead: "The right remote partner affects how products look on PDPs, ads, and social — and how fast teams ship.",
    whyVisual: "linear-gradient(160deg,#1a1220,#111),radial-gradient(circle at 40% 40%,rgba(227,6,19,0.38),transparent 50%)",
    why: [
      { title: "Commerce-grade precision", text: "Color consistency, overlay alignment, and brand lock across PDP, ads, and social." },
      { title: "Format-aware judgment", text: "UGC authenticity vs. demo clarity vs. launch polish — not one generic style." },
      { title: "Platform-ready exports", text: "Specs for Shopify, Amazon, YouTube, TikTok, and paid social packs." },
      { title: "Advanced craft on demand", text: "Motion callouts and title packages scoped before Checkout." },
      { title: "Remote volume infrastructure", text: "Cloud handoff and version labeling for SKU batches." },
      { title: "Performance-informed structure", text: "Hook early, feature clearly, close with action." },
    ],
    ctaTitle: "Managing product video quality across platforms is operational — we finish it remotely.",
    ctaBody: "Reduce post overhead, keep brand consistency, and deliver at volume with human editorial oversight.",
    inquiryTitle: "Request a Product Video Scope",
    inquiryLead: "Share SKU volume, platforms, and deadline. Hours or package confirmed before Stripe.",
    bottomTitle: "Ready to finish product videos that convert?",
    contactTopic: "product",
    faqs: [
      { q: "Do you edit agency-shot product demos?", a: "Yes — stabilize, grade, structure, and deliver with revision rounds listed in scope." },
      { q: "What upgrades are typically included?", a: "Color, transitions, audio, overlays, captions, and platform packs as listed." },
      { q: "Can you handle fluctuating SKU volume?", a: "Yes. Queued remote handoffs and brand templates keep batches consistent." },
      { q: "How long does it take?", a: "Depends on footage and depth. Schedules are shared at intake." },
      { q: "How is brand consistency kept?", a: "Brand kits locked at kickoff; finals cleared against that kit." },
    ],
  },
  {
    slug: "testimonial",
    label: "Testimonial Video",
    eyebrow: "Testimonial video editing",
    metaTitle: "Testimonial Video Editing Services",
    metaDescription: "Remote testimonial finishing that keeps social proof real and brand-clean. Clear USD pricing before Stripe.",
    heroLines: ["Testimonial finishing", "that keeps proof real"],
    heroDescription: "Structure client footage into consistent, brand-aligned testimonial films — remote delivery, published pricing, Stripe-secured checkout.",
    image: "https://images.unsplash.com/photo-1600880292203-757bb62b4baf?auto=format&fit=crop&w=900&q=80",
    aspect: "tall",
    introTitle: "Social proof only works when it’s clear and credible",
    introBody: "Raw interviews drift, meander, and break brand. We shape testimonials into concise narratives with brand polish — without making customers sound scripted.",
    introAside: "Ideal for SaaS, agencies, and service brands that need proof clips for websites, ads, and sales decks.",
    menuTitle: "Testimonial Editing Services",
    menuLead: "From raw interviews to landing-page-ready proof — scope you can buy with clarity.",
    offerings: [
      { title: "Narrative Testimonial Films", featured: true, image: g("#1a2030", "rgba(227,6,19,0.35)"), bullets: ["Story arc: problem → solution → outcome", "Selective trimming of off-topic tangents", "Brand lower-thirds and name cards", "Master + short social cut-downs"] },
      { title: "Quote & Soundbite Packs", image: g("#201818", "rgba(255,138,0,0.25)"), bullets: ["Pull strongest lines for ads and decks", "Captioned verticals for social", "Still frame quote cards where scoped", "Organized delivery folders by use case"] },
      { title: "Multi-Speaker Case Narratives", image: g("#181a22", "rgba(56,120,180,0.3)"), bullets: ["Blend customer + internal voices", "B-roll integration from supplied assets", "Consistent grade across cameras", "Chaptered long-form where needed"] },
      { title: "Landing Page Proof Edits", image: g("#1a1418", "rgba(227,6,19,0.28)"), bullets: ["Sub-60s and hero-block lengths", "Muted autoplay-friendly masters", "Logo end-cards per brand kit", "WebM / MP4 export options"] },
      { title: "Review Round Polish", image: g("#14181a", "rgba(61,191,176,0.2)"), bullets: ["Stakeholder time-coded feedback", "Legal / compliance text overlays", "Version locks before publish", "SRT captions for accessibility"] },
      { title: "UGC Testimonial Clean-Up", image: g("#1a1814", "rgba(255,193,7,0.2)"), bullets: ["Phone footage stabilize & denoise", "Brand-safe color and framing", "Aspect packs for feed and stories", "CTA beats for paid social"] },
    ],
    whyEyebrow: "Credibility craft",
    whyTitle: "Why Teams Trust Our Testimonial Finishing",
    whyLead: "Proof that feels human and still looks on-brand — delivered online.",
    whyVisual: "linear-gradient(160deg,#201218,#111),radial-gradient(circle at 40% 40%,rgba(227,6,19,0.3),transparent 50%)",
    why: [
      { title: "Authenticity preserved", text: "We protect natural speech while removing noise that kills trust." },
      { title: "Brand compliance", text: "Titles, logos, and color stay inside your kit." },
      { title: "Sales-ready lengths", text: "Cuts sized for site, ads, and decks in one engagement." },
      { title: "Remote review loops", text: "Frame.io or time-coded notes — no office visit." },
      { title: "Caption clarity", text: "On-screen text and SRTs for silent autoplay and accessibility." },
      { title: "Clear commercial terms", text: "Hours or packages confirmed before Stripe." },
    ],
    ctaTitle: "Turn client interviews into proof that ships.",
    ctaBody: "Remote finishing with revision rounds you can plan around — and USD totals you approve first.",
    inquiryTitle: "Request a Testimonial Scope",
    inquiryLead: "Share interview lengths, platforms, and brand kit status.",
    bottomTitle: "Ready to make social proof land?",
    contactTopic: "testimonial",
    faqs: [
      { q: "Can you edit multilingual testimonials?", a: "Yes when transcripts or guidance are provided. Caption languages are scoped at intake." },
      { q: "Do you invent customer quotes?", a: "No. We only use spoken or approved transcript content." },
      { q: "What if legal wants disclosure text?", a: "We add supplied compliance text as overlays in the agreed rounds." },
      { q: "Typical turnaround?", a: "Set at intake — often in line with Essential/Pro package ranges." },
      { q: "Remote handoff?", a: "Drive, Dropbox, Frame.io, or WeTransfer — fully online." },
    ],
  },
  {
    slug: "real-estate",
    label: "Real Estate Video Tour",
    eyebrow: "Real estate video editing",
    metaTitle: "Real Estate Video Tour Editing",
    metaDescription: "Remote editing for property tours, drone finishes, and listing verticals with clear USD pricing.",
    heroLines: ["Property tour finishing", "that shows space clearly"],
    heroDescription: "Stabilize, sequence, and brand property tours for portals, agents, and paid social — remote delivery with platform-ready exports.",
    image: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=900&q=80",
    aspect: "short",
    introTitle: "Listings move faster when the tour feels effortless",
    introBody: "Horizon drift, exposure jumps, and meandering walk-throughs lose buyers. We finish real estate footage into chaptered tours and vertical clips agents can publish confidently.",
    introAside: "For brokerages, photographers, and proptech teams outsourcing post — without a walk-in studio.",
    menuTitle: "Real Estate Video Editing Services",
    menuLead: "From single listings to portal batches — scoped remote finishing.",
    offerings: [
      { title: "Full Property Tour Finishing", featured: true, image: g("#1a1814", "rgba(255,138,0,0.28)"), bullets: ["Stabilize and horizon-correct room-to-room", "Logical room sequencing with soft transitions", "Title cards and address treatments", "Master horizontal tour for portals"] },
      { title: "Drone & Exterior Assembly", image: g("#141a18", "rgba(56,120,180,0.3)"), bullets: ["Aerial select and pacing", "Exposure match to interiors", "Music beds within licensed libraries", "Highlight cut for social teasers"] },
      { title: "Vertical Listing Reels", image: g("#1a1418", "rgba(227,6,19,0.28)"), bullets: ["9:16 cuts for IG / TikTok / portals", "Caption hooks for features & price", "Loop-friendly endings", "Batch naming for multi-listing drops"] },
      { title: "Luxury / Staging Polish", image: g("#181820", "rgba(227,6,19,0.22)"), bullets: ["Premium grade and contrast control", "Detail close-ups sequenced intentionally", "Agent / brokerage end-cards", "Web + presentation masters"] },
      { title: "Multi-Unit / Portfolio Batches", image: g("#161414", "rgba(61,191,176,0.2)"), bullets: ["Template-locked intros for brand consistency", "Queue-friendly remote intake", "Per-unit folders and labels", "Revision protocol for broker feedback"] },
      { title: "Matterport / Screen Capture Hybrid", image: g("#1a1814", "rgba(255,193,7,0.18)"), bullets: ["Integrate supplied walkthrough captures", "Callout overlays for amenities", "Music and VO leveling", "Portal-safe compressions"] },
    ],
    whyEyebrow: "Listing craft",
    whyTitle: "Why Agents Choose Our Tour Finishing",
    whyLead: "Clear space, fast turnaround, portal-ready files — finished online.",
    whyVisual: "linear-gradient(160deg,#1a1814,#111),radial-gradient(circle at 50% 40%,rgba(255,138,0,0.25),transparent 50%)",
    why: [
      { title: "Spatial clarity", text: "Room order and pacing that help buyers understand the home." },
      { title: "Technical cleanup", text: "Stabilization, exposure balance, and horizon fixes that reduce DIY stigma." },
      { title: "Portal packs", text: "Horizontals and verticals ready for MLS-adjacent marketing." },
      { title: "Brand lock", text: "Brokerage end-cards and colors applied consistently." },
      { title: "Remote handoff", text: "Drop footage online; get publishable tours back." },
      { title: "Batch friendly", text: "Templates for high-volume listing weeks." },
    ],
    ctaTitle: "Ship listing tours without blocking photographers on post.",
    ctaBody: "Remote queue, clear scopes, and USD confirmed before payment.",
    inquiryTitle: "Request a Real Estate Edit Scope",
    inquiryLead: "Share listing count, drone availability, and delivery platforms.",
    bottomTitle: "Ready to finish your next tour?",
    contactTopic: "video",
    faqs: [
      { q: "Phone + drone mixes OK?", a: "Yes — we match color and pace across sources where footage allows." },
      { q: "Music licensing?", a: "Royalty-free beds included when scoped; client libraries on request." },
      { q: "Rush listing weekend?", a: "Rush is available when capacity is confirmed at intake." },
      { q: "Vertical-only jobs?", a: "Yes — reels-only packages are common." },
      { q: "How do I send files?", a: "Drive, Dropbox, or WeTransfer — fully remote." },
    ],
  },
  {
    slug: "social-shorts",
    label: "Social Shorts / Reels",
    eyebrow: "Social shorts editing",
    metaTitle: "Social Shorts & Reels Editing",
    metaDescription: "Remote Reels, TikTok, and Shorts finishing with captions, hooks, and platform packs.",
    heroLines: ["Short-form finishing", "built for the feed"],
    heroDescription: "Hooks, captions, and platform ratios for Reels, TikTok, and Shorts — remote editors who cut for retention, not just length.",
    image: "https://images.unsplash.com/photo-1611162616471-46b635cb1dd1?auto=format&fit=crop&w=900&q=80",
    aspect: "wide",
    introTitle: "Short-form fails when the first two seconds don’t earn the next eight",
    introBody: "We cut vertical content with intentional hooks, on-screen text, and safe-zone framing — then pack exports for each network.",
    introAside: "For brands, creators, and agencies running always-on social calendars remotely.",
    menuTitle: "Social Shorts Editing Services",
    menuLead: "From raw clips to scheduled-ready verticals.",
    offerings: [
      { title: "Reels / TikTok / Shorts Packs", featured: true, image: g("#1a1020", "rgba(227,6,19,0.4)"), bullets: ["9:16 masters with safe margins", "Hook-first openings", "Burned-in or sidecar captions", "Per-platform exports"] },
      { title: "Talking-Head Social Cuts", image: g("#201818", "rgba(255,138,0,0.25)"), bullets: ["Jump-cut polish", "Denoise and level VO", "Text callouts on key lines", "Pattern interrupts for retention"] },
      { title: "UGC Social Adaptation", image: g("#181a22", "rgba(56,120,180,0.3)"), bullets: ["Brand-safe grade on creator clips", "Logo and CTA end cards", "Aspect reframes", "Batch calendars for campaigns"] },
      { title: "Product / Offer Social Spots", image: g("#1a1418", "rgba(227,6,19,0.28)"), bullets: ["Benefit-first pacing", "Price / offer overlays", "Music beds licensed for social", "A/B ending variants when scoped"] },
      { title: "Carousel & Multi-Clip Sets", image: g("#14181a", "rgba(61,191,176,0.2)"), bullets: ["Series storytelling across posts", "Consistent title system", "Folderized deliveries", "Scheduling naming conventions"] },
      { title: "Always-On Retainer Shorts", image: g("#1a1814", "rgba(255,193,7,0.2)"), bullets: ["Weekly capacity blocks", "Shared brief templates", "Priority queue notes", "Cancel terms per policy"] },
    ],
    whyEyebrow: "Feed craft",
    whyTitle: "Why Teams Outsource Shorts Finishing",
    whyLead: "Volume without looking templated — remote, fast, measurable.",
    whyVisual: "linear-gradient(160deg,#1a1020,#111),radial-gradient(circle at 40% 40%,rgba(227,6,19,0.35),transparent 50%)",
    why: [
      { title: "Hook discipline", text: "Openings designed for scroll-stopping clarity." },
      { title: "Caption first", text: "Most viewers watch muted — text is part of the cut." },
      { title: "Safe framing", text: "UI chrome won’t cover faces or CTAs." },
      { title: "Batch delivery", text: "Calendar packs that social managers can schedule." },
      { title: "Brand control", text: "LUTs and end-cards stay consistent." },
      { title: "Remote velocity", text: "Cloud review, no office bottlenecks." },
    ],
    ctaTitle: "Keep the feed full without burning your in-house editors.",
    ctaBody: "Scoped vertical packs with USD totals confirmed before Stripe.",
    inquiryTitle: "Request a Shorts Scope",
    inquiryLead: "Tell us platforms, weekly volume, and brand kit status.",
    bottomTitle: "Ready to scale short-form finishing?",
    contactTopic: "video",
    faqs: [
      { q: "Native vertical only?", a: "We prefer native 9:16. Letterboxed conversions are available if needed." },
      { q: "Do you write scripts?", a: "Editing focus — scripts can be client-supplied or lightly punched up when scoped." },
      { q: "Music?", a: "Royalty-free beds or your licensed tracks." },
      { q: "Subtitles language?", a: "As provided; translation is a separate scope." },
      { q: "Turnaround?", a: "Often faster than long-form — confirmed at intake." },
    ],
  },
  {
    slug: "youtube",
    label: "YouTube Long-Form",
    eyebrow: "YouTube long-form editing",
    metaTitle: "YouTube Long-Form Editing Services",
    metaDescription: "Remote YouTube editing with chapters, thumbnails support cuts, end screens, and retention pacing.",
    heroLines: ["Long-form finishing", "built for watch time"],
    heroDescription: "Structure, pace, and polish YouTube episodes remotely — chapters, captions, end-screen beats, and brand-consistent openers.",
    image: "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&w=900&q=80",
    aspect: "short",
    introTitle: "Long-form only works when the middle doesn’t lose the open",
    introBody: "We cut episodes for clarity and retention: cold opens, chapter beats, B-roll densification, and clean audio — then deliver masters ready for YouTube Studio.",
    introAside: "For creators, educators, and brand channels outsourcing post without hiring full-time editors.",
    menuTitle: "YouTube Editing Services",
    menuLead: "Episode finishing that respects length and still earns the next watch.",
    offerings: [
      { title: "Full Episode Assembly", featured: true, image: g("#1a1820", "rgba(227,6,19,0.32)"), bullets: ["Cold open + branded intro", "Chapter markers and pacing notes", "B-roll insert and lower-thirds", "End screen / subscribe beats"] },
      { title: "Multi-Cam / Podcast YouTube", image: g("#201818", "rgba(255,138,0,0.25)"), bullets: ["Angle switching for energy", "Audio leveling and denoise", "Guest name plates", "Highlight shorts cutdowns"] },
      { title: "Educational / Tutorial Structure", image: g("#181a22", "rgba(56,120,180,0.3)"), bullets: ["Step sequencing with on-screen labels", "Screen-share cleanup", "Chapter titles for SEO", "Summary cards where scoped"] },
      { title: "Series Template Systems", image: g("#1a1418", "rgba(227,6,19,0.28)"), bullets: ["Locked openers and bumpers", "Consistent title treatments", "Faster episode turnarounds", "Brand kit enforcement"] },
      { title: "Caption & Accessibility Packs", image: g("#14181a", "rgba(61,191,176,0.2)"), bullets: ["Burned-in or SRT captions", "Speaker IDs when needed", "Silent-friendly text emphasis", "Language as supplied"] },
      { title: "Shorts from Long-Form", image: g("#1a1814", "rgba(255,193,7,0.2)"), bullets: ["Hook harvest from masters", "9:16 reframes", "Captioned verticals", "Episode CTA backlinks in text"] },
    ],
    whyEyebrow: "Channel craft",
    whyTitle: "Why Creators Outsource YouTube Post",
    whyLead: "Publish cadence without sacrificing editorial discipline.",
    whyVisual: "linear-gradient(160deg,#1a1820,#111),radial-gradient(circle at 45% 40%,rgba(227,6,19,0.3),transparent 50%)",
    why: [
      { title: "Retention pacing", text: "Cuts that protect the middle of long episodes." },
      { title: "Chapter clarity", text: "Structure that helps SEO and human skimming." },
      { title: "Audio first", text: "Clean dialogue beats fancy graphics for most niches." },
      { title: "Series consistency", text: "Templates so episode 12 looks like episode 1." },
      { title: "Shorts harvest", text: "Clips that feed discovery from the same masters." },
      { title: "Remote queue", text: "Upload online; review with time codes." },
    ],
    ctaTitle: "Protect your publish calendar with remote episode finishing.",
    ctaBody: "Scoped per episode or retainer blocks — USD confirmed before Stripe.",
    inquiryTitle: "Request a YouTube Edit Scope",
    inquiryLead: "Share average runtime, series frequency, and brand kit links.",
    bottomTitle: "Ready to finish your next upload?",
    contactTopic: "video",
    faqs: [
      { q: "Do you design thumbnails?", a: "Thumbnail stills can be exported; full design is scoped separately." },
      { q: "Multi-hour live VODs?", a: "Yes — we scope highlight or chaptered cutdowns." },
      { q: "Music?", a: "Royalty-free or client-licensed tracks only." },
      { q: "Revision rounds?", a: "Listed in your package or custom quote." },
      { q: "File handoff?", a: "Drive / Dropbox / Frame.io — fully remote." },
    ],
  },
  {
    slug: "saas-demo",
    label: "SaaS Product Demos",
    eyebrow: "SaaS demo video editing",
    metaTitle: "SaaS Product Demo Video Editing",
    metaDescription: "Remote SaaS demo and feature video finishing for websites, sales decks, and ads.",
    heroLines: ["Demo finishing", "that makes features land"],
    heroDescription: "Screen captures, VO, and UI callouts shaped into crisp product demos for GTM, sales, and self-serve pages — remote delivery.",
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=900&q=80",
    aspect: "mid",
    introTitle: "SaaS demos fail when the UI talks louder than the value",
    introBody: "We structure feature footage into benefit-led narratives with zoom beats, callouts, and clean audio — so buyers understand the product faster.",
    introAside: "For product marketing, founders, and agencies shipping demo assets across launch windows.",
    menuTitle: "SaaS Demo Editing Services",
    menuLead: "From screen recordings to sales-ready masters.",
    offerings: [
      { title: "Website Demo Masters", featured: true, image: g("#141a22", "rgba(56,120,180,0.35)"), bullets: ["Benefit-first narrative structure", "Cursor / zoom emphasis on key clicks", "UI callout overlays", "Muted autoplay-friendly cuts"] },
      { title: "Feature Drop Series", image: g("#1a1418", "rgba(227,6,19,0.28)"), bullets: ["Repeatable template per release", "Changelog-friendly pacing", "Social vertical companions", "Brand-locked end cards"] },
      { title: "Sales Enablement Cuts", image: g("#201818", "rgba(255,138,0,0.25)"), bullets: ["Persona-specific paths", "Objection-handling beats", "Deck-insert lengths", "Chaptered long demos"] },
      { title: "Founder / VE Narrative Hybrid", image: g("#181820", "rgba(227,6,19,0.22)"), bullets: ["Talking head + UI intercuts", "Script sync and jump cuts", "Lower-thirds for roles", "CTA for trial / book demo"] },
      { title: "Onboarding Explainer Edits", image: g("#14181a", "rgba(61,191,176,0.2)"), bullets: ["Step sequencing", "Safe defaults callouts", "Caption support", "Help-center friendly lengths"] },
      { title: "Paid Social Demo Spots", image: g("#1a1814", "rgba(255,193,7,0.2)"), bullets: ["Hook → value → CTA in under 30s", "Platform ratios", "Offer overlays", "A/B openings when scoped"] },
    ],
    whyEyebrow: "GTM craft",
    whyTitle: "Why Product Teams Use Our Demo Finishing",
    whyLead: "Clarity for buyers. Consistency for brand. Speed for launch weeks.",
    whyVisual: "linear-gradient(160deg,#141a22,#111),radial-gradient(circle at 40% 40%,rgba(56,120,180,0.35),transparent 50%)",
    why: [
      { title: "Value over UI tourism", text: "We cut for outcomes, not every click." },
      { title: "Launch velocity", text: "Templates ready when feature flags flip." },
      { title: "Sales alignment", text: "Lengths that fit decks and demo rooms." },
      { title: "Brand lock", text: "Colors, logos, and motion language stay consistent." },
      { title: "Remote security-friendly", text: "Cloud handoff — no walk-in requirement." },
      { title: "Clear commercials", text: "Hours or packages before Stripe." },
    ],
    ctaTitle: "Ship demos that sell the product, not just show the UI.",
    ctaBody: "Remote finishing with revision rounds you can plan into launch checklists.",
    inquiryTitle: "Request a SaaS Demo Scope",
    inquiryLead: "Share product area, runtime target, and where the asset will live.",
    bottomTitle: "Ready to finish your next feature film?",
    contactTopic: "video",
    faqs: [
      { q: "NDAs?", a: "Standard confidentiality via our terms; custom NDAs on request." },
      { q: "Do you record the product?", a: "We edit supplied captures; recording is out of scope unless arranged." },
      { q: "Motion graphics depth?", a: "UI callouts and simple motion included; heavy 3D is scoped separately." },
      { q: "Languages?", a: "VO and captions in languages you provide." },
      { q: "Turnaround?", a: "Confirmed at intake against your launch date." },
    ],
  },
  {
    slug: "wedding-event",
    label: "Wedding / Event Highlights",
    eyebrow: "Wedding & event video finishing",
    metaTitle: "Wedding & Event Highlight Editing",
    metaDescription: "Remote wedding and event highlight finishing with teaser cuts and full-day structures.",
    heroLines: ["Event highlight finishing", "with emotional pacing"],
    heroDescription: "Shape ceremony, reception, and corporate event footage into films couples and planners can rewatch — remote post with clear scopes.",
    image: "https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=900&q=80",
    aspect: "tall",
    introTitle: "Highlights fail when every moment fights for equal time",
    introBody: "We select for emotion and pace: vows, reactions, details, and dance-floor energy — finished remotely for couples, planners, and AV teams.",
    introAside: "For wedding filmmakers and event producers who shoot hard and need reliable post partners.",
    menuTitle: "Wedding & Event Editing Services",
    menuLead: "Teasers, highlights, and full-assembly scopes online.",
    offerings: [
      { title: "Highlight Films", featured: true, image: g("#1a1418", "rgba(227,6,19,0.3)"), bullets: ["Emotional arc selection", "Color grade to wedding aesthetic", "Licensed or client music sync", "Master + vertical teaser"] },
      { title: "Teaser / Social Cuts", image: g("#201818", "rgba(255,138,0,0.25)"), bullets: ["Same-week teaser options when scoped", "9:16 and square exports", "Captioned couple names", "Planner portfolio lengths"] },
      { title: "Ceremony & Speech Assembly", image: g("#181a22", "rgba(56,120,180,0.3)"), bullets: ["Clean audio priority", "Guest reaction inserts", "Chaptered long cuts", "Family delivery masters"] },
      { title: "Corporate Event Films", image: g("#14181a", "rgba(61,191,176,0.2)"), bullets: ["Keynote + floor energy", "Sponsor brand compliance", "Recap lengths for LinkedIn", "Multi-day selects"] },
      { title: "Multi-Cam Event Sync", image: g("#1a1820", "rgba(227,6,19,0.22)"), bullets: ["Timecode-friendly assembly", "Angle hygiene", "Stage graphics cleanup", "Livestream VOD polish"] },
      { title: "Season Batch for Filmmakers", image: g("#1a1814", "rgba(255,193,7,0.2)"), bullets: ["Template-locked style per brand", "Queue-friendly remote intake", "Per-couple folders", "Revision protocol for couples"] },
    ],
    whyEyebrow: "Emotion craft",
    whyTitle: "Why Filmmakers Partner With Us on Post",
    whyLead: "Protect your shoot reputation with reliable finishing.",
    whyVisual: "linear-gradient(160deg,#1a1418,#111),radial-gradient(circle at 50% 35%,rgba(227,6,19,0.28),transparent 50%)",
    why: [
      { title: "Emotional selection", text: "We cut for feeling, not exhaustive coverage." },
      { title: "Audio respect", text: "Vows and speeches stay intelligible." },
      { title: "Style lock", text: "Match your signature grade across seasons." },
      { title: "Teaser speed", text: "Social cuts that keep couples engaged." },
      { title: "Remote season capacity", text: "Scale post without new hires." },
      { title: "Clear client terms", text: "Scopes and revisions defined up front." },
    ],
    ctaTitle: "Finish more weddings without sleeping in the suite.",
    ctaBody: "Remote highlight partners with USD confirmed before payment.",
    inquiryTitle: "Request a Wedding / Event Scope",
    inquiryLead: "Share shoot date, expected highlight length, and music preferences.",
    bottomTitle: "Ready to hand off your next highlight?",
    contactTopic: "video",
    faqs: [
      { q: "Rush same-week teaser?", a: "Available when capacity is confirmed at booking." },
      { q: "Music licensing?", a: "Client-licensed preferred for weddings; RF options when scoped." },
      { q: "Raw archival delivery?", a: "Yes — organized selects folders when listed in scope." },
      { q: "Corporate vs wedding?", a: "Both — brand events follow corporate compliance rules." },
      { q: "How to send footage?", a: "Drive / Dropbox / WeTransfer — fully remote." },
    ],
  },
  {
    slug: "sales-pitch",
    label: "Sales Pitch Video",
    eyebrow: "Sales pitch video editing",
    metaTitle: "Sales Pitch Video Editing Services",
    metaDescription: "Remote sales pitch and proposal video finishing for decks, outbound, and buyer portals.",
    heroLines: ["Pitch films", "that sell the next meeting"],
    heroDescription: "Tighten founder and AE pitches into crisp outbound films — problem, proof, ask — with brand polish and remote delivery.",
    image: "https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=900&q=80",
    aspect: "mid",
    introTitle: "Pitch videos die when they sound like a meeting room recording",
    introBody: "We reshape sales narratives into confident, buyer-facing films with clear CTAs — for outbound, RFP responses, and investor or partner decks.",
    introAside: "For revenue teams and founders who need pitch media without a production department.",
    menuTitle: "Sales Pitch Editing Services",
    menuLead: "Outbound-ready cuts with commercial clarity.",
    offerings: [
      { title: "Outbound Pitch Films", featured: true, image: g("#1a1418", "rgba(227,6,19,0.32)"), bullets: ["Problem → value → proof arc", "Jump-cut polish on talking heads", "Offer / CTA end cards", "Email-friendly compressions"] },
      { title: "RFP / Proposal Video Inserts", image: g("#181a22", "rgba(56,120,180,0.3)"), bullets: ["Chaptered capability sections", "Compliance text overlays", "Logo walls for clients", "PDF-deck companion lengths"] },
      { title: "Persona Variants", image: g("#201818", "rgba(255,138,0,0.25)"), bullets: ["Shared master + persona opens", "Industry callouts", "Localized CTAs", "Batch naming for CRMs"] },
      { title: "Founder Narrative Pitches", image: g("#14181a", "rgba(61,191,176,0.2)"), bullets: ["Story + product hybrid", "B-roll of product or team", "Subtle grade for credibility", "Investor or partner endings"] },
      { title: "Live Pitch VOD Clean-Up", image: g("#1a1820", "rgba(227,6,19,0.22)"), bullets: ["Trim dead air", "Slide sync cleanup", "Audience Q cutdowns", "Internal vs external masters"] },
      { title: "Sales Pod Retainer Cuts", image: g("#1a1814", "rgba(255,193,7,0.2)"), bullets: ["Monthly capacity for AEs", "Template locks", "Fast personalization swaps", "SLA notes in scope"] },
    ],
    whyEyebrow: "Revenue craft",
    whyTitle: "Why Revenue Teams Buy Pitch Finishing",
    whyLead: "Faster personalization. Stronger first impressions. Less AE camera shame.",
    whyVisual: "linear-gradient(160deg,#1a1418,#111),radial-gradient(circle at 40% 40%,rgba(227,6,19,0.32),transparent 50%)",
    why: [
      { title: "Narrative discipline", text: "Buyers get value before features dump." },
      { title: "Credible polish", text: "Enough production value to trust — not film-school fluff." },
      { title: "Variant speed", text: "Persona and offer swaps without full recuts." },
      { title: "CRM-friendly files", text: "Sizes and naming sales ops can track." },
      { title: "Remote handoff", text: "Record anywhere; we finish online." },
      { title: "Clear pricing", text: "USD confirmed before Stripe." },
    ],
    ctaTitle: "Turn AE recordings into films buyers actually watch.",
    ctaBody: "Scoped pitch packs with revision rounds listed up front.",
    inquiryTitle: "Request a Sales Pitch Scope",
    inquiryLead: "Share use case (outbound, RFP, investor) and target length.",
    bottomTitle: "Ready to sharpen your next pitch?",
    contactTopic: "video",
    faqs: [
      { q: "Can you remove filler words heavily?", a: "Yes within natural speech limits — we protect authenticity." },
      { q: "Slide deck overlays?", a: "When slides are supplied, we intercut or overlay as scoped." },
      { q: "Multiple languages?", a: "VO/captions as provided." },
      { q: "NDA for pipeline deals?", a: "Covered by standard terms; custom NDAs available." },
      { q: "Turnaround?", a: "Often aligned to outbound cadence — confirmed at intake." },
    ],
  },
  {
    slug: "interview",
    label: "Interview & Leadership",
    eyebrow: "Interview & leadership video editing",
    metaTitle: "Interview & Leadership Video Editing",
    metaDescription: "Remote finishing for leadership interviews, podcasts-to-video, and executive communications.",
    heroLines: ["Leadership interviews", "finished for credibility"],
    heroDescription: "Clean multi-cam interviews, executive messages, and thought-leadership cuts — remote editors who protect presence and brand.",
    image: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=900&q=80",
    aspect: "tall",
    introTitle: "Leadership video fails when delivery looks unrehearsed and unmanaged",
    introBody: "We finish interviews and executive films with respectful jump cuts, audio polish, and title systems that match corporate brand standards.",
    introAside: "For internal comms, PR, and founder brands shipping authority content online.",
    menuTitle: "Interview Editing Services",
    menuLead: "From raw sits to publishable leadership films.",
    offerings: [
      { title: "Executive Interview Films", featured: true, image: g("#181820", "rgba(227,6,19,0.28)"), bullets: ["Story selects from long sits", "Respectful jump-cut hygiene", "Name/title lower-thirds", "Web + LinkedIn masters"] },
      { title: "Internal Leadership Messages", image: g("#201818", "rgba(255,138,0,0.25)"), bullets: ["Town-hall cutdowns", "Captioned intranet versions", "Slide / graphic inserts", "Multi-language text when supplied"] },
      { title: "Podcast-to-Video", image: g("#141a22", "rgba(56,120,180,0.3)"), bullets: ["Waveform or static + talking head", "Clip harvesting for social", "Guest plates", "Show brand lock"] },
      { title: "Panel & Roundtable Edits", image: g("#1a1418", "rgba(227,6,19,0.28)"), bullets: ["Multi-speaker clarity", "Question chaptering", "Audience reaction trims", "Highlight reels"] },
      { title: "Thought-Leadership Series", image: g("#14181a", "rgba(61,191,176,0.2)"), bullets: ["Template openers", "Consistent grade", "CTA to blog / newsletter", "Batch episode delivery"] },
      { title: "PR / Media Sit Clean-Up", image: g("#1a1814", "rgba(255,193,7,0.2)"), bullets: ["B-roll integration", "Legal/disclaimer text", "Broadcast-safe audio", "Press kit stills exports"] },
    ],
    whyEyebrow: "Presence craft",
    whyTitle: "Why Comms Teams Outsource Interview Finishing",
    whyLead: "Protect executive presence. Ship on message calendars.",
    whyVisual: "linear-gradient(160deg,#181820,#111),radial-gradient(circle at 45% 40%,rgba(227,6,19,0.28),transparent 50%)",
    why: [
      { title: "Presence first", text: "Edits that make leaders look prepared, not overproduced." },
      { title: "Message control", text: "Selects aligned to approved talking points." },
      { title: "Brand titles", text: "Lower-thirds and end-cards locked to kit." },
      { title: "Multi-channel packs", text: "Long + social from one sit." },
      { title: "Confidential remote workflow", text: "Secure cloud handoff for sensitive messages." },
      { title: "Clear scope", text: "Revisions and hours confirmed before payment." },
    ],
    ctaTitle: "Finish leadership sits before the news cycle moves on.",
    ctaBody: "Remote interview partners with published USD options.",
    inquiryTitle: "Request an Interview Edit Scope",
    inquiryLead: "Share runtime, speakers, and whether social cutdowns are required.",
    bottomTitle: "Ready to publish leadership with polish?",
    contactTopic: "video",
    faqs: [
      { q: "Can you hide teleprompter glances?", a: "Within reason via selects and reframes — we flag limits upfront." },
      { q: "Green screen?", a: "Keying available when footage supports clean edges." },
      { q: "Sensitive internal only?", a: "Yes — watermarked drafts and private review links." },
      { q: "Caption languages?", a: "As provided in the brief." },
      { q: "Turnaround?", a: "Confirmed against your publish window." },
    ],
  },
  {
    slug: "campaign",
    label: "Campaign Re-Editing",
    eyebrow: "Campaign re-editing",
    metaTitle: "Campaign Re-Editing Services",
    metaDescription: "Remote campaign adaptation — cutdowns, ratio packs, and localization for paid and organic.",
    heroLines: ["Campaign adaptations", "without restarting post"],
    heroDescription: "Re-cut masters into platform packs, offer variants, and market adaptations — remote finishing when media plans change mid-flight.",
    image: "https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?auto=format&fit=crop&w=900&q=80",
    aspect: "short",
    introTitle: "Campaigns don’t fail at shoot — they stall at adaptation",
    introBody: "We take existing masters and produce ratio packs, length variants, and offer swaps so media teams can test without net-new production.",
    introAside: "For performance marketers, agencies, and brand teams living in always-on calendars.",
    menuTitle: "Campaign Re-Editing Services",
    menuLead: "Masters in. Platform packs out.",
    offerings: [
      { title: "Ratio & Length Packs", featured: true, image: g("#1a1020", "rgba(227,6,19,0.35)"), bullets: ["16:9 / 1:1 / 9:16 reframes", "6s / 15s / 30s cutdowns", "Safe-zone QA", "Naming for ad platforms"] },
      { title: "Offer / Hook Variants", image: g("#201818", "rgba(255,138,0,0.25)"), bullets: ["Opening hook swaps", "Price and promo overlays", "End-card CTA versions", "A/B-ready folders"] },
      { title: "Localization Adaptations", image: g("#181a22", "rgba(56,120,180,0.3)"), bullets: ["Supers and VO swaps", "Market text as supplied", "Legal line updates", "Region folder delivery"] },
      { title: "Organic Companion Cuts", image: g("#1a1418", "rgba(227,6,19,0.28)"), bullets: ["Softer CTA versions", "Behind-the-scenes trims", "Creator-style reframes", "Community caption packs"] },
      { title: "Legacy Master Rescue", image: g("#14181a", "rgba(61,191,176,0.2)"), bullets: ["Stabilize and grade refresh", "Audio cleanup", "Modern title systems", "New logo end-cards"] },
      { title: "Always-On Adaptation Retainer", image: g("#1a1814", "rgba(255,193,7,0.2)"), bullets: ["Weekly swap capacity", "Shared brief template", "Priority notes", "Cancel terms per policy"] },
    ],
    whyEyebrow: "Media craft",
    whyTitle: "Why Media Teams Use Campaign Re-Editing",
    whyLead: "Test more. Waste less shoot budget. Ship mid-flight changes.",
    whyVisual: "linear-gradient(160deg,#1a1020,#111),radial-gradient(circle at 40% 40%,rgba(227,6,19,0.32),transparent 50%)",
    why: [
      { title: "Master efficiency", text: "One shoot fuels months of media math." },
      { title: "Platform hygiene", text: "Ratios and safe zones done right." },
      { title: "Test velocity", text: "Hook and offer swaps without creative delays." },
      { title: "Localization care", text: "Market supers without breaking brand." },
      { title: "Remote collaboration", text: "Frame.io or time-coded notes." },
      { title: "Transparent scope", text: "Variant counts priced before Stripe." },
    ],
    ctaTitle: "Stop letting adaptation queues kill your CPA tests.",
    ctaBody: "Remote campaign packs with clear USD and revision rules.",
    inquiryTitle: "Request a Campaign Adaptation Scope",
    inquiryLead: "Share master count, platforms, and variant matrix.",
    bottomTitle: "Ready to adapt the next flight?",
    contactTopic: "video",
    faqs: [
      { q: "Do you need project files?", a: "Masters + brand kit usually suffice; project files help for deep reopen." },
      { q: "How many variants?", a: "Priced by matrix size — confirmed at intake." },
      { q: "Legal supers?", a: "We place text you supply in approved placements." },
      { q: "Rush for flight dates?", a: "Yes when capacity is open." },
      { q: "Organic + paid together?", a: "Common — delivered in separate folders." },
    ],
  },
  {
    slug: "travel",
    label: "Travel & Lifestyle Film",
    eyebrow: "Travel & lifestyle editing",
    metaTitle: "Travel & Lifestyle Film Editing",
    metaDescription: "Remote travel and lifestyle film finishing for brands, creators, and destination partners.",
    heroLines: ["Travel films", "with editorial wanderlust"],
    heroDescription: "Pace destination footage into lifestyle stories for brands and creators — grade, music sync, and platform packs finished remotely.",
    image: "https://images.unsplash.com/photo-1506923821422-49322bed9b4b?auto=format&fit=crop&w=900&q=80",
    aspect: "mid",
    introTitle: "Travel footage is cheap. Editorial taste is not",
    introBody: "We select destinations into narrative sequences with cinematic grade and intentional stillness — not every clip earns a place.",
    introAside: "For tourism boards, hotels, outdoor brands, and creators outsourcing post.",
    menuTitle: "Travel & Lifestyle Editing",
    menuLead: "From raw travel days to publishable films.",
    offerings: [
      { title: "Destination Story Films", featured: true, image: g("#141a18", "rgba(61,191,176,0.28)"), bullets: ["Location arc and pacing", "Cinematic grade", "Music sync and sound beds", "Master + social teasers"] },
      { title: "Hotel / Property Lifestyle Cuts", image: g("#1a1814", "rgba(255,138,0,0.25)"), bullets: ["Amenity sequencing", "Guest journey beats", "OTA-friendly lengths", "Vertical packs"] },
      { title: "Creator Travel Vlogs", image: g("#1a1418", "rgba(227,6,19,0.28)"), bullets: ["Talking-head + B-roll hybrid", "Jump-cut energy", "Captioned verticals", "Sponsor integration slots"] },
      { title: "Brand Outdoor Films", image: g("#181a22", "rgba(56,120,180,0.3)"), bullets: ["Product-in-environment selects", "Action pacing", "Logo end-cards", "Campaign cutdowns"] },
      { title: "Reel / Short Destination Packs", image: g("#201818", "rgba(255,193,7,0.2)"), bullets: ["Hook-first verticals", "Music bed options", "Location title cards", "Batch series delivery"] },
      { title: "Seasonal Campaign Adapts", image: g("#14181a", "rgba(61,191,176,0.2)"), bullets: ["Holiday supers", "Offer overlays", "Ratio packs", "Region variants"] },
    ],
    whyEyebrow: "Wander craft",
    whyTitle: "Why Travel Brands Trust Our Finishing",
    whyLead: "Atmosphere without chaos. Grade that sells the place.",
    whyVisual: "linear-gradient(160deg,#141a18,#111),radial-gradient(circle at 50% 40%,rgba(61,191,176,0.3),transparent 50%)",
    why: [
      { title: "Selective storytelling", text: "We cut destination films, not dump cards." },
      { title: "Grade with intent", text: "Look that matches place and brand." },
      { title: "Platform packs", text: "Long + short without double shoots." },
      { title: "Music taste", text: "Beds that fit mood and licensing rules." },
      { title: "Remote season capacity", text: "Peak travel weeks without local studio bottlenecks." },
      { title: "Clear commercials", text: "Scope and USD before payment." },
    ],
    ctaTitle: "Turn travel days into films that book the next trip.",
    ctaBody: "Remote lifestyle finishing with revision rounds you can plan.",
    inquiryTitle: "Request a Travel Film Scope",
    inquiryLead: "Share destination, intended length, and brand references.",
    bottomTitle: "Ready to finish your next destination story?",
    contactTopic: "video",
    faqs: [
      { q: "Drone + phone mixes?", a: "Yes — we match pace and grade across sources." },
      { q: "Music licensing?", a: "RF beds or your licensed tracks." },
      { q: "Multi-location series?", a: "Template systems available for seasons." },
      { q: "Sponsored disclosures?", a: "We place text you supply." },
      { q: "Turnaround?", a: "Confirmed at intake against publish date." },
    ],
  },
  {
    slug: "photo-catalog",
    label: "Photo Catalog Retouch",
    eyebrow: "Catalog photo retouching",
    metaTitle: "Product Catalog Photo Retouching",
    metaDescription: "Remote catalog retouching for ecommerce — color, cleanup, and batch consistency with clear USD pricing.",
    heroLines: ["Catalog retouching", "at merchandising speed"],
    heroDescription: "Batch-ready product still finishing for Shopify, marketplaces, and lookbooks — remote delivery with brand-locked standards.",
    image: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=900&q=80",
    aspect: "mid",
    introTitle: "Catalogs look cheap when every SKU has a different white",
    introBody: "We retouch product stills for consistency: cleanup, color, soft shadows, and export sizes that merchandising teams can drop straight onto PDPs.",
    introAside: "For ecommerce brands, studios, and agencies outsourcing still post at volume.",
    menuTitle: "Catalog Retouching Services",
    menuLead: "SKU-ready stills with batch discipline.",
    offerings: [
      { title: "Batch Catalog Cleanup", featured: true, image: g("#1a1814", "rgba(255,138,0,0.28)"), bullets: ["Dust, thread, and scuff removal", "Color consistency across SKUs", "Edge cleanup and fringe control", "Export sizes per channel"] },
      { title: "Ghost Mannequin / Hollow", image: g("#181a22", "rgba(56,120,180,0.3)"), bullets: ["Neck joint finishing", "Symmetry corrections", "Natural volume shadows", "Apparel category packs"] },
      { title: "Colorway / Swatch Sets", image: g("#1a1418", "rgba(227,6,19,0.28)"), bullets: ["Match to brand standards", "Side-by-side consistency", "Filename conventions", "QC spot checks"] },
      { title: "Lifestyle Still Polish", image: g("#14181a", "rgba(61,191,176,0.2)"), bullets: ["Skin and product balance", "Background tidy", "Creative grade options", "Campaign still exports"] },
      { title: "Lookbook Sequence Finishing", image: g("#201818", "rgba(255,193,7,0.2)"), bullets: ["Tone matched across pages", "Soft cleanup without plastic look", "Print + web dual masters", "Credit title frames if scoped"] },
      { title: "Always-On Catalog Retainer", image: g("#141820", "rgba(227,6,19,0.22)"), bullets: ["Weekly SKU capacity", "Shared SOP checklist", "Priority drop windows", "Cancel terms per policy"] },
    ],
    whyEyebrow: "Still craft",
    whyTitle: "Why Merchandising Teams Choose Us",
    whyLead: "Consistent whites. Honest products. Files named for ops.",
    whyVisual: "linear-gradient(160deg,#1a1814,#111),radial-gradient(circle at 45% 40%,rgba(255,138,0,0.28),transparent 50%)",
    why: [
      { title: "Batch consistency", text: "SKUs look like one catalog, not twelve freelancers." },
      { title: "Honest retouch", text: "Cleanup without misrepresenting materials." },
      { title: "Channel exports", text: "Sizes ready for web and marketplace." },
      { title: "SOP adherence", text: "Your checklist becomes our checklist." },
      { title: "Remote volume", text: "Drop shoots online; get publishable packs." },
      { title: "Clear pricing", text: "Per-image or package USD before Stripe." },
    ],
    ctaTitle: "Keep PDPs shipping while photo volume spikes.",
    ctaBody: "Remote catalog finishing with QC standards you can audit.",
    inquiryTitle: "Request a Catalog Retouch Scope",
    inquiryLead: "Share SKU count, background rules, and export specs.",
    bottomTitle: "Ready to finish the next drop?",
    contactTopic: "photo",
    faqs: [
      { q: "Per-image pricing?", a: "Yes — or package blocks for volume. Confirmed before payment." },
      { q: "Complex jewelry reflections?", a: "Scoped depth depends on detail level — we sample first when needed." },
      { q: "File formats?", a: "JPEG/PNG/TIFF as requested; PSD on request." },
      { q: "Rush launches?", a: "Available when capacity is confirmed." },
      { q: "How to send?", a: "Drive / Dropbox — fully remote." },
    ],
  },
  {
    slug: "commerce-pathing",
    label: "Commerce Pathing",
    eyebrow: "Marketplace pathing & still prep",
    metaTitle: "Marketplace Pathing & Commerce Photo Prep",
    metaDescription: "Remote Amazon and marketplace pathing, background, and compliance-ready still finishing.",
    heroLines: ["Marketplace pathing", "built for listing compliance"],
    heroDescription: "White backgrounds, shadow standards, and main-image packs for Amazon and marketplace listings — remote still finishing with QC checklists.",
    image: "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?auto=format&fit=crop&w=900&q=80",
    aspect: "tall",
    introTitle: "Listings get suppressed when heroes break marketplace rules",
    introBody: "We prepare commerce stills for pathing and listing: pure backgrounds, correct margins, shadow discipline, and secondary image sets that convert.",
    introAside: "For Amazon sellers, agencies, and brands managing multi-marketplace catalogs.",
    menuTitle: "Commerce Pathing Services",
    menuLead: "Listing-ready heroes and secondary packs.",
    offerings: [
      { title: "Main Image Pathing", featured: true, image: g("#181820", "rgba(227,6,19,0.3)"), bullets: ["Pure white / required backgrounds", "Margin and fill compliance", "Soft natural shadows", "Naming for ASIN workflows"] },
      { title: "Secondary Infographic Stills", image: g("#201818", "rgba(255,138,0,0.25)"), bullets: ["Feature callout layouts", "Brand-safe icon sets", "Dimension graphics", "A+ module companions"] },
      { title: "Multi-Marketplace Packs", image: g("#181a22", "rgba(56,120,180,0.3)"), bullets: ["Amazon / Walmart / Shopify variants", "Spec matrix exports", "Region folder delivery", "QC checklist sign-off"] },
      { title: "Apparel Flat & Path Combos", image: g("#1a1418", "rgba(227,6,19,0.28)"), bullets: ["Ghost + flat coordination", "Colorway heroes", "Detail crops", "Listing secondary sets"] },
      { title: "Listing Refresh Batches", image: g("#14181a", "rgba(61,191,176,0.2)"), bullets: ["Competitor-gap still upgrades", "Lifestyle insert polish", "Updated logo treatments", "Bulk ASIN queues"] },
      { title: "Agency Overflow Retainer", image: g("#1a1814", "rgba(255,193,7,0.2)"), bullets: ["Weekly image capacity", "Shared brand SOPs", "Priority ASIN lists", "Transparent revision rules"] },
    ],
    whyEyebrow: "Listing craft",
    whyTitle: "Why Sellers Outsource Pathing",
    whyLead: "Compliance first. Conversion second. Drama never.",
    whyVisual: "linear-gradient(160deg,#181820,#111),radial-gradient(circle at 40% 40%,rgba(227,6,19,0.3),transparent 50%)",
    why: [
      { title: "Compliance literacy", text: "Heroes built to marketplace rules you’ve approved." },
      { title: "Shadow standards", text: "Natural, not muddy or floating." },
      { title: "Pack discipline", text: "Main + secondary delivered ready to upload." },
      { title: "ASIN-friendly naming", text: "Ops can find files without Slack archaeology." },
      { title: "Remote scale", text: "Launch weeks without local retoucher bottlenecks." },
      { title: "Clear USD", text: "Per image or packs confirmed before Stripe." },
    ],
    ctaTitle: "Stop losing Buy Box potential to soft white backgrounds.",
    ctaBody: "Remote pathing with checklists you can QA against.",
    inquiryTitle: "Request a Pathing Scope",
    inquiryLead: "Share marketplace list, image counts, and brand SOPs.",
    bottomTitle: "Ready to path the next ASIN batch?",
    contactTopic: "photo",
    faqs: [
      { q: "Do you guarantee Amazon approval?", a: "We follow your stated specs; final listing approval is Amazon’s." },
      { q: "Infographic design depth?", a: "Layout within template systems; heavy design may be scoped separately." },
      { q: "PSD delivery?", a: "Available when requested." },
      { q: "Rush?", a: "Yes with capacity confirmation." },
      { q: "Handoff?", a: "Cloud folders — fully remote." },
    ],
  },
  {
    slug: "headshots",
    label: "Headshots & Team",
    eyebrow: "Headshot & team photo finishing",
    metaTitle: "Headshot & Team Photo Retouching",
    metaDescription: "Remote headshot and team still finishing for websites, press, and directories — natural, consistent, brand-safe.",
    heroLines: ["Headshot finishing", "that looks like your people"],
    heroDescription: "Natural retouching for executives, teams, and directories — consistent backgrounds and lighting matches finished remotely.",
    image: "https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=900&q=80",
    aspect: "wide",
    introTitle: "Team pages look unprofessional when every headshot is a different universe",
    introBody: "We finish headshots for consistency: skin that still looks human, background harmony, and crop systems for web and LinkedIn.",
    introAside: "For HR, internal brand, agencies, and studios outsourcing headshot post.",
    menuTitle: "Headshot Retouching Services",
    menuLead: "People-first still finishing with brand locks.",
    offerings: [
      { title: "Executive Headshot Polish", featured: true, image: g("#181820", "rgba(227,6,19,0.28)"), bullets: ["Natural skin cleanup", "Stray hair and lint tidy", "Eye clarity without overcook", "Web + print crops"] },
      { title: "Team Consistency Packs", image: g("#201818", "rgba(255,138,0,0.25)"), bullets: ["Matched backgrounds", "Lighting balance across sessions", "Uniform crop ratios", "Directory-ready naming"] },
      { title: "LinkedIn / Press Variants", image: g("#181a22", "rgba(56,120,180,0.3)"), bullets: ["Platform crop packs", "Slightly warmer press grades", "High-res masters", "Filename conventions for PR"] },
      { title: "Studio Session Overflow", image: g("#1a1418", "rgba(227,6,19,0.28)"), bullets: ["Select + retouch workflow", "Client gallery prep", "Batch QC", "Rush windows when scoped"] },
      { title: "Background Replacement Light", image: g("#14181a", "rgba(61,191,176,0.2)"), bullets: ["Clean seamless swaps", "Soft contact shadows", "Brand color backgrounds", "Edge-safe hair work"] },
      { title: "Annual Directory Retainer", image: g("#1a1814", "rgba(255,193,7,0.2)"), bullets: ["Quarterly new-hire batches", "SOP-locked style", "Priority HR drops", "Cancel terms per policy"] },
    ],
    whyEyebrow: "People craft",
    whyTitle: "Why Brands Trust Our Headshot Finishing",
    whyLead: "Believable people. Consistent directories. No plasticky skin.",
    whyVisual: "linear-gradient(160deg,#181820,#111),radial-gradient(circle at 45% 40%,rgba(227,6,19,0.28),transparent 50%)",
    why: [
      { title: "Natural retouch", text: "We clean — we don’t invent new faces." },
      { title: "Team harmony", text: "Directories look intentional." },
      { title: "Crop systems", text: "Web, press, and LinkedIn without rework." },
      { title: "Sensitive workflow", text: "Private remote handoff for people photos." },
      { title: "Studio partnership", text: "Overflow when your booking book is full." },
      { title: "Clear pricing", text: "Per-image or packs before Stripe." },
    ],
    ctaTitle: "Make the about page look as sharp as the product.",
    ctaBody: "Remote headshot finishing with natural standards.",
    inquiryTitle: "Request a Headshot Scope",
    inquiryLead: "Share headcount, background preference, and crop needs.",
    bottomTitle: "Ready to finish your next team set?",
    contactTopic: "photo",
    faqs: [
      { q: "How heavy is retouching?", a: "Natural by default — heavier beauty on request." },
      { q: "Glasses glare?", a: "Reduced when recoverable; rebuilds scoped if severe." },
      { q: "Group composites?", a: "Available as a separate scope." },
      { q: "Turnaround?", a: "Often fast for small batches — confirmed at intake." },
      { q: "Delivery?", a: "Cloud folders — fully remote." },
    ],
  },
  {
    slug: "cartoonic",
    label: "Cartoonic Video Editing",
    eyebrow: "Cartoonic & stylized video finishing",
    metaTitle: "Cartoonic Video Editing Services",
    metaDescription: "Remote cartoonic and stylized video finishing for explainer, kids, and brand mascot content with clear USD pricing.",
    heroLines: ["Cartoonic finishing", "with character and clarity"],
    heroDescription: "Shape cartoon-style explainers, mascot clips, and stylized brand films — remote editing that keeps motion readable and on-brand.",
    image: "https://images.unsplash.com/photo-1633356122544-f134324a6cee?auto=format&fit=crop&w=900&q=80",
    aspect: "tall",
    introTitle: "Cartoon content fails when style and message fight each other",
    introBody: "We finish cartoonic and stylized footage so characters stay consistent, timing feels playful, and the story still sells — without looking like a random clip dump.",
    introAside: "For agencies, educators, kids brands, and startups that need cartoon-led explainers delivered online.",
    menuTitle: "Cartoonic Editing Services",
    menuLead: "From rough animatics and renders to publish-ready cartoon films.",
    offerings: [
      { title: "Cartoon Explainer Finishing", featured: true, image: g("#1a1020", "rgba(227,6,19,0.35)"), bullets: ["Scene pacing and beat sync", "VO / music leveling", "Title and caption packs", "Web + social masters"] },
      { title: "Mascot & Character Clips", image: g("#201818", "rgba(255,138,0,0.25)"), bullets: ["Character continuity checks", "Loop-friendly social cuts", "Brand color lock", "CTA end cards"] },
      { title: "Kids / Education Series", image: g("#181a22", "rgba(56,120,180,0.3)"), bullets: ["Soft grade for youth audiences", "On-screen learning labels", "Episode template systems", "Safe pacing and volume"] },
      { title: "Stylized Live + Cartoon Hybrid", image: g("#1a1418", "rgba(227,6,19,0.28)"), bullets: ["Composite timing cleanup", "Transition polish", "Mixed-media balance", "Platform ratio packs"] },
      { title: "Animatic to Final Polish", image: g("#14181a", "rgba(61,191,176,0.2)"), bullets: ["Replace placeholders with finals", "Timing lock to approved animatic", "SFX and whoosh beds", "Revision-controlled deliveries"] },
      { title: "Always-On Cartoon Retainer", image: g("#1a1814", "rgba(255,193,7,0.2)"), bullets: ["Weekly episode capacity", "Shared style bible", "Priority queue notes", "Cancel terms per policy"] },
    ],
    whyEyebrow: "Character craft",
    whyTitle: "Why Teams Choose Cartoonic Finishing",
    whyLead: "Playful motion with adult commercial discipline.",
    whyVisual: "linear-gradient(160deg,#1a1020,#111),radial-gradient(circle at 40% 40%,rgba(227,6,19,0.35),transparent 50%)",
    why: [
      { title: "Style consistency", text: "Characters and colors stay locked to your bible." },
      { title: "Story first", text: "We cut for clarity, not just cute frames." },
      { title: "Audio discipline", text: "VO and SFX sit clean for kids and adults alike." },
      { title: "Series templates", text: "Episode 8 still looks like episode 1." },
      { title: "Remote delivery", text: "Cloud review — no walk-in studio required." },
      { title: "Clear commercials", text: "USD and revision rounds before Stripe." },
    ],
    ctaTitle: "Ship cartoonic films that feel fun and still convert.",
    ctaBody: "Remote cartoon finishing with scopes you can brief once and reuse.",
    inquiryTitle: "Request a Cartoonic Scope",
    inquiryLead: "Share style references, runtime, and whether VO / music are supplied.",
    bottomTitle: "Ready to finish your next cartoon film?",
    contactTopic: "video",
    faqs: [
      { q: "Do you draw characters from scratch?", a: "We finish and edit supplied animation / assets. New character design is scoped separately." },
      { q: "Can you edit After Effects or Premiere exports?", a: "Yes — masters, project packages, or rendered sequences as agreed at intake." },
      { q: "Music for kids content?", a: "Royalty-free beds or your licensed tracks only." },
      { q: "Multi-language versions?", a: "VO / caption swaps when assets are provided." },
      { q: "Typical turnaround?", a: "Confirmed at intake against episode length and complexity." },
    ],
  },
  {
    slug: "animation-2d",
    label: "2D Animation Video Editing",
    eyebrow: "2D animation video finishing",
    metaTitle: "2D Animation Video Editing Services",
    metaDescription: "Remote 2D animation finishing — explainer edits, motion graphics polish, and platform packs with clear USD pricing.",
    heroLines: ["2D animation finishing", "built for explainers"],
    heroDescription: "Assemble, time, and polish 2D animation and motion graphics for explainers, ads, and product stories — remote with brand-locked deliverables.",
    image: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=900&q=80",
    aspect: "mid",
    introTitle: "2D work looks expensive until the edit exposes weak timing",
    introBody: "We finish 2D animation packages so beats sync to VO, graphics land clean, and exports survive web, ads, and social without quality loss.",
    introAside: "For motion designers, agencies, and product marketers who need reliable post on 2D pipelines.",
    menuTitle: "2D Animation Editing Services",
    menuLead: "From AE exports and vector scenes to campaign-ready masters.",
    offerings: [
      { title: "2D Explainer Assembly", featured: true, image: g("#141a22", "rgba(56,120,180,0.35)"), bullets: ["Scene timing to VO", "Transition and wipe polish", "Lower-thirds and captions", "Master + cutdown packs"] },
      { title: "Motion Graphics Polish", image: g("#1a1418", "rgba(227,6,19,0.28)"), bullets: ["Logo stings and bumpers", "Kinetic type cleanup", "Brand kit color lock", "Loop-safe social versions"] },
      { title: "UI / Product 2D Stories", image: g("#201818", "rgba(255,138,0,0.25)"), bullets: ["Screen-flow narrative", "Callout overlays", "Benefit-first pacing", "Muted autoplay cuts"] },
      { title: "Ad & Paid Social 2D Spots", image: g("#181820", "rgba(227,6,19,0.22)"), bullets: ["Hook-first openings", "6s / 15s / 30s variants", "Safe-zone QA", "Offer overlay swaps"] },
      { title: "Series Template Systems", image: g("#14181a", "rgba(61,191,176,0.2)"), bullets: ["Locked openers and end cards", "Faster episode turnarounds", "Naming for ops", "Style bible enforcement"] },
      { title: "2D Finishing Retainer", image: g("#1a1814", "rgba(255,193,7,0.2)"), bullets: ["Weekly capacity blocks", "Shared brief template", "Priority GTM notes", "Cancel terms per policy"] },
    ],
    whyEyebrow: "Motion craft",
    whyTitle: "Why Teams Outsource 2D Finishing",
    whyLead: "Timing, audio, and platform packs — without burning your motion designers on export chores.",
    whyVisual: "linear-gradient(160deg,#141a22,#111),radial-gradient(circle at 45% 40%,rgba(56,120,180,0.35),transparent 50%)",
    why: [
      { title: "Beat-accurate timing", text: "Animation lands with VO and music, not against them." },
      { title: "Brand lock", text: "Colors, type, and logos stay inside the kit." },
      { title: "Export discipline", text: "Clean masters for web, paid, and organic." },
      { title: "Designer relief", text: "Your motion team designs; we finish and pack." },
      { title: "Remote review", text: "Time-coded notes and cloud folders." },
      { title: "Transparent scope", text: "Hours or packages confirmed before Stripe." },
    ],
    ctaTitle: "Finish 2D explainers that feel designed — and ship on schedule.",
    ctaBody: "Remote 2D animation editing with revision rounds listed up front.",
    inquiryTitle: "Request a 2D Animation Scope",
    inquiryLead: "Share project files or renders, VO status, and target platforms.",
    bottomTitle: "Ready to finish your next 2D piece?",
    contactTopic: "video",
    faqs: [
      { q: "Do you animate from scratch?", a: "Primary scope is finishing / editing supplied 2D. Full animation production can be quoted separately." },
      { q: "After Effects projects OK?", a: "Yes when versions and fonts are shared; otherwise rendered sequences work." },
      { q: "Lottie / web formats?", a: "Available when scoped — otherwise standard video masters." },
      { q: "Multi-language?", a: "VO and caption variants when assets are provided." },
      { q: "Turnaround?", a: "Depends on length and revision depth — set at intake." },
    ],
  },
  {
    slug: "animation-3d",
    label: "3D Animation Video Editing",
    eyebrow: "3D animation video finishing",
    metaTitle: "3D Animation Video Editing Services",
    metaDescription: "Remote 3D animation and product viz finishing — edit, grade, composite polish, and platform packs with clear USD pricing.",
    heroLines: ["3D video finishing", "that sells form and motion"],
    heroDescription: "Cut, grade, and package 3D product viz, architectural films, and CGI spots — remote finishing with commercial-grade audio and export control.",
    image: "https://images.unsplash.com/photo-1633356122102-3fe601e15448?auto=format&fit=crop&w=900&q=80",
    aspect: "wide",
    introTitle: "3D looks premium until the edit exposes flat pacing and muddy audio",
    introBody: "We finish 3D renders into cinematic or commercial films: camera beat selection, grade, composite cleanup, and masters that hold up on PDPs, decks, and paid social.",
    introAside: "For CGI studios, product teams, architecture firms, and agencies that need reliable post on 3D pipelines.",
    menuTitle: "3D Animation Editing Services",
    menuLead: "From multi-pass renders to client-ready 3D films.",
    offerings: [
      { title: "3D Product / Viz Films", featured: true, image: g("#181820", "rgba(227,6,19,0.32)"), bullets: ["Shot select and pace", "Grade for materials and metal", "Logo / CTA end cards", "Web + presentation masters"] },
      { title: "Architectural / Real-Estate CGI", image: g("#141a18", "rgba(61,191,176,0.28)"), bullets: ["Space sequencing", "Day-to-night beats when supplied", "Music and ambience beds", "Portal + social cutdowns"] },
      { title: "Composite & Pass Assembly", image: g("#181a22", "rgba(56,120,180,0.3)"), bullets: ["Beauty / AO / specular timing", "Edge and glow tidy", "Plate integration polish", "Version locks for approvals"] },
      { title: "Tech / Industrial 3D Spots", image: g("#1a1418", "rgba(227,6,19,0.28)"), bullets: ["Feature callout overlays", "Exploded-view pacing", "Safety / compliance text", "Deck-insert lengths"] },
      { title: "Paid Social 3D Packs", image: g("#201818", "rgba(255,138,0,0.25)"), bullets: ["Hook-first verticals", "Ratio safe-zones", "Offer overlay variants", "Loop-friendly endings"] },
      { title: "Studio Overflow Retainer", image: g("#1a1814", "rgba(255,193,7,0.2)"), bullets: ["Weekly finishing capacity", "Shared naming SOPs", "Priority client queues", "Cancel terms per policy"] },
    ],
    whyEyebrow: "CGI craft",
    whyTitle: "Why 3D Teams Hand Us Finishing",
    whyLead: "Protect render beauty. Ship commercial clarity. Scale overflows.",
    whyVisual: "linear-gradient(160deg,#181820,#111),radial-gradient(circle at 40% 40%,rgba(227,6,19,0.3),transparent 50%)",
    why: [
      { title: "Material-aware grade", text: "Metals, glass, and plastics stay believable." },
      { title: "Commercial pacing", text: "Shots earn their length; nothing drifts." },
      { title: "Composite care", text: "Passes assembled cleanly for approval rounds." },
      { title: "Platform packs", text: "One film fuels web, decks, and ads." },
      { title: "Remote overflow", text: "Your artists render; we finish online." },
      { title: "Clear pricing", text: "USD confirmed before Stripe." },
    ],
    ctaTitle: "Turn expensive renders into films buyers understand.",
    ctaBody: "Remote 3D finishing with revision control built for client reviews.",
    inquiryTitle: "Request a 3D Finishing Scope",
    inquiryLead: "Share render lengths, pass availability, and delivery platforms.",
    bottomTitle: "Ready to finish your next 3D film?",
    contactTopic: "video",
    faqs: [
      { q: "Do you model or render in-house?", a: "We finish supplied 3D. Modeling / lighting / rendering can be quoted as a separate production scope." },
      { q: "EXR / multi-pass workflows?", a: "Yes when passes and naming are documented at intake." },
      { q: "Heavy VFX sims?", a: "Complex fluid / destruction finishing is scoped after a sample review." },
      { q: "Music and SFX?", a: "Royalty-free beds or your libraries — listed in scope." },
      { q: "Turnaround?", a: "Driven by shot count and grade depth — confirmed at intake." },
    ],
  },
];

export function getServiceBySlug(slug: string) {
  return serviceCatalog.find((s) => s.slug === slug);
}

export function getAllServiceSlugs() {
  return serviceCatalog.map((s) => s.slug);
}

export const serviceCatalogCategories = serviceCatalog.map((s) => ({
  title: s.label,
  href: `/services/${s.slug}`,
  image: s.image,
  aspect: s.aspect,
}));
